export const products = [
  {
    type: "Software",
    name: "Adobe after effects 2022",
    weight: "2.45 Go",
    year: "06/22",
    version: "v22.5.0.53",
    link: "https://www5.yggtorrent.fi/torrent/application/windows/920132-adobe+after+effects+2022+v22+5+0+53+windows+x64+multilang",
    price: 15,
    image:
      "https://image.noelshack.com/fichiers/2022/31/5/1659701330-4d1c4e051d96c74bc36626749f4a6a4b.png",
    description:
      "Créez des graphismes et des effets visuels incroyables avec Adobe After Effects. Conception pour le cinéma, la télévision, la vidéo  et le web; Avec After Effects, l’application d’animation et d’effets spéciaux de référence, rendez vos vidéos et vos scènes vraiment uniques. Créez des titres, des introductions et des transitions cinématographiques, retirez un objet d’un plan, animez un logo ou un personnage et explorez toutes  les possibilités offertes par l’espace 3D.<br><br>•Processeur : Processeur multicœur Intel ou AMD<br>•Système d'exploitation : Microsoft Windows 10 (64 bits) version 1909 et ultérieure.<br>•RAM : 16 Go ou plus (32 Go recommandés)<br>•GPU : 2 Go de VRAM GPU (4 Go ou plus recommandés)<br>Espace disque : 15 Go d'espace libre sur le disque dur ; espace libre supplémentaire requis lors de l'installation (l'installation sur des •périphériques de stockage flash amovibles n'est pas prise en charge). Espace disque supplémentaire pour la mise en cache du disque (64 Go ou plus recommandés)<br>•Résolution du moniteur : Résolution du moniteur de 1920 x 1080 pixels ou supérieure<br>•Langue : Multi",
  },
  {
    year: "06/22",
    type: "Software",
    name: "topaz video enhance AI 2.6.3 Repack",
    weight: "2.72 Go",
    version: "2.6.3",
    link: "https://www5.yggtorrent.fi/torrent/application/windows/864517-topaz+video+enhance+ai+2+6+3+repack+portable+win+en+pr%C3%89activ%C3%89",
    price: 15,
    image:
      "https://1.bp.blogspot.com/-n4WIBDgJ54E/YSoxb3FQqpI/AAAAAAAAN5k/Kd_YYASEuQwVSSlWjK5otzisLENJ9iX2gCLcBGAsYHQ/s600/Topaz-Video-Enhance-AI.jpeg",
    description:
      "Topaz Video Enhance AI est une toute nouvelle solution d'amélioration vidéo utilisant l'intelligence artificielle. Formé avec des milliers de vidéos et combinant les informations de plusieurs  images vidéo d'entrée, Topaz Video Enhance AI élèvera votre vidéo à une  résolution de 8K avec des détails précis et une cohérence de mouvement.  Jusqu'à présent, il n'était pas possible de recréer parfaitement une vidéo  haute définition à partir de séquences basse définition.  Video Enhance AI transforme vos vidéos en séquences nettes et mises à  l'échelle jusqu'à 8K, des vieux films personnels aux SD et DVD de faible  qualité.<br><br>•Année de parution : 2022<br>•  Version : 2.6.3 (17/02/2022)<br>•  Site : Topaz Lab<br>•  Langue de l'interface : Anglais<br><br>Configuration : <br>•Windows 10 & 11 - 64 bits uniquement<br>•OpenGL version 3.3 ou supérieure<br>•Intel i5 (7e génération) ou équivalent (3.0 GHz et plus)<br>•Ryzen 5 (Ryzen 7 ou plus) équivalent (3,0 GHz et plus)<br>•Nvidia GTX 1080 (8 Go) ou plus<br>•RAM 8 Go (Recommandé : 16 Go)",
  },
  {
    year: "11/21",
    type: "Software",
    name: "Adobe premiere Pro 2022",
    weight: "1.66Go",
    version: "v22.0.0.111",
    link: "https://www5.yggtorrent.fi/torrent/application/windows/828536-adobe+premiere+pro+2022+v22+0+0+169+win+x64+multi+pre-activated",
    price: 15,
    image: "https://i.imgur.com/zJU13WN.png",
    description:
      "Adobe Premiere Pro gère de nombreux formats vidéo et intègre un système de scénarimage (storyboard) très complet. C'est un logiciel de montage virtuel comme Avid ou Final Cut Pro. Depuis la version « Pro », de nombreuses améliorations ont été apportées, en particulier une stabilité accrue. Son principal atout est les liens avec les autres produits Adobe (très utilisés dans le monde professionnel), tels que Encore, After Effects ou Photoshop.<br><br>•Editeur: Adobe<br>•Système d'exploitation: Windows 10 (ou plus)<br>•Version : v22.0.0.169 <br><br>Configuration: <br>•Architecture :  64 bits    <br>•Processeur :  Intel 6eme génération, AMD Ryzen série 1000, GPU 2Go<br>•Mémoire vive :  4 Go<br>•Disque Dur :  30Go espace disque<br>•Carte Graphique :  4 Go ",
  },
  {
    year: "08/21",
    type: "Software",
    name: "Adobe photoshop elements",
    weight: "3.85Go",
    version: "2021.3",
    link: "https://www5.yggtorrent.fi/torrent/application/windows/794063-adobe+photoshop+elements+v2021+3+win+x64+multi-fr+activ%C3%A9",
    price: 15,
    image: "https://i.ibb.co/8jbvmqR/Photoshop-Elements.png",
    description:
      "Des retouches et montages intelligents. Des photos et vidéos irréprochables. Des créations originales.<br><br>•Nom : Adobe Photoshop Elements v2021.3<br>•Editeur : Adobe<br>•Publié le : 08/21<br>•Version : 2021.3<br>•Compatible : Windows  10  ",
  },
  {
    year: "08/21",
    type: "Software",
    name: "Magix Vegas pro v19",
    weight: "899Mo",
    version: "19.0.0.341",
    link: "https://www5.yggtorrent.fi/torrent/application/windows/792412-magix+vegas+pro+v19+0+0+341+multi-fr+win+x64+crack",
    price: 15,
    image: "https://www8.0zz0.com/2021/11/25/16/369377808.jpg",
    description:
      "Offre de nombreuses fonctions d'édition et de traitement<br>Animations de suivi de mouvement progressifInteraction dynamique entre le scénarimage et la Timeline<br>Stabilisation d'image de premier ordre<br>Prise en charge des couleurs HDR<br>Mise en place de plusieurs caméras pour un maximum de 32 sources vidéo<br>Vitesse de lecture variable de -100% à +300%.<br>Support d'ACES 1.0<br>Nombre illimité de pistes vidéo<br>Accélération matérielle avec support Intel QSV et accélération GPU<br>Plug-in Picture-in-Picture, LUT et Plug-in Crop OFX<br>Création instantanée d'images fixes par Freeze<br>Montage de projet vidéo 360°<br>Masques décoratifs Bézier Plug-in OFX<br>Environnement audio multipiste complet<br>Plus de 390 effets vidéo et 30 effets audio<br>Mélangeur Surround avec contrôle de panoramique<br>Codage 5.1 et Dolby AC3 stéréo intégré<br>Prise en charge des pilotes ASIO et des plug-ins VST2<br><br>Description: <br>•Nom : MAGIX VEGAS Pro v19.0.0.341<br>•Publié le : 08/21<br>•Editeur : MAGIX<br>•Version : 19.0.0.341<br>•Compatible : Windows 7 8 10<br>•Licence : Payante<br><br>Configuration:<br>•Systeme d'exploitation : Windows 7 /8/ 10<br>•Architecture : 64 bits<br>•Processeur : 2 Go Intel 6eme génération, AMD Ryzen série 1000, GPU 2Go<br>•Memoire vive : 1 Go<br>•Disque Dur : 2 Go espace disque<br>•Résolution d'écran : 1280x800",
  },
  {
    year: "04/21",
    type: "Software Bundle",
    name: "Adobe Master Collection cc 2021 v3",
    weight: "21.52Go",
    pack: [
      { name: "Adobe Acrobat DC 2021", version: "2021.001.20155", weight: "" },
      { name: "Adobe After Effects 2021", version: "18.2.0.37" },
      { name: "Adobe Animate 2021", version: "21.0.6.41649" },
      { name: "Adobe Audition 2021", version: "14.2.0.34" },
      { name: "Adobe Bridge 2021", version: "11.0.2.123" },
      { name: "Adobe Character Animator 2021", version: "4.2.0.34" },
      { name: "Adobe Dimension", version: "3.4.2.4011" },
      { name: "Adobe Dreamweaver 2021", version: "21.1.0.15413" },
      { name: "Adobe Illustrator 2021", version: "25.2.3.259" },
      { name: "Adobe InCopy 2021", version: "16.2.1.102" },
      { name: "Adobe InDesign 2021", version: "16.2.1.102" },
      { name: "Adobe Lightroom Classic", version: "10.2.0.202103041821" },
      { name: "Adobe Media Encoder 2021", version: "15.2.0.30" },
      { name: "Adobe Photoshop 2021", version: "22.4.0.195" },
      { name: "Adobe Prelude 2021", version: "10.0.0.34" },
      { name: "Adobe Premiere Pro 2021", version: "15.2.0.35" },
      { name: "Adobe XD", version: "40.0.22" },
      { name: "Adobe Creative Cloud Core", version: "5.4.5.550" },
      { name: "Adobe Camera Raw", version: "13.2.0.73" },
    ],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/761962-adobe+master+collection+cc+avril+2021+multi+v11+4+pr%C3%A9-activ%C3%A9",
    price: 15,
    image:
      "https://play-lh.googleusercontent.com/FucKbk9_x0Kt4kkaN9dvHjdIwBEPTrl3Z8DevY2UJczs1Uk8EMC93VXOYVn_Vr5mBQ",
    description:
      "Adobe Creative Cloud est un ensemble d'applications et de services proposés par Adobe Systems, qui permet aux abonnés d'accéder à une collection de logiciels utilisés pour la conception graphique, le montage vidéo, le développement web, la photographie, un ensemble d'applications mobiles, et des services cloud",
  },
  {
    year: "03/21",
    type: "Software",
    name: "Blackmagic Design DaVinci Resolve Studio v17.1.0.24",
    weight: "2.77Go",
    version: "v17.1.0.24",
    link: "https://www5.yggtorrent.fi/torrent/application/windows/734578-blackmagic+design+davinci+resolve+studio+v17+1+0+24+win+x64+multi+crack",
    price: 15,
    image: "https://i.gyazo.com/0ef7bfdf682fc9b5ffd092cd99ba01af.jpg",
    description:
      "DaVinci Resolve est la seule solution qui associe le montage, l’étalonnage, les effets visuels, les animations graphiques et la  post-production audio dans un seul logiciel. Son interface moderne et  élégante est à la fois simple à utiliser pour les débutants et  performante pour les professionnels. DaVinci Resolve vous permet de  travailler plus rapidement et dans une meilleure qualité, car vous  n’avez pas besoin de vous familiariser avec plusieurs applications ou de  changer de logiciel selon la tâche à effectuer. Vous pouvez donc vous  servir des images originales des caméras durant tout le workflow. C’est comme disposer de votre propre studio de post-production au sein d’une  seule application. De plus, avec DaVinci Resolve, vous utiliserez les  mêmes outils que les professionnels d’Hollywood !<br><br>Informations générales:<br>•Type : Logiciel de solutions de montage, d’étalonnage, mixage<br>•Langue : Multi (Français Inclus)<br>•Plateforme : Windows 10 Pro x64<br>•Taille : 2.77 GO<br>•Nombre de Fichiers: 5<br>•Année de sortie : 2020",
  },
  {
    year: "02/21",
    type: "Software",
    name: "Magix Video DeLuxe 2021 premium",
    weight: "820Mo",
    version: "20.0.73",
    link: "https://www5.yggtorrent.fi/torrent/application/windows/725666-magix+video+deluxe+2021+premium",
    price: 15,
    image: "https://nsa40.casimages.com/img/2021/02/21/210221091434133449.png",
    description:
      "Magix Video DeLuxe est un logiciel de montage vidéo très célèbre et excellent développé par MAGIX Software. Son interface utilisateur est élégante, intuitive et conviviale, et n’est inférieure à aucun logiciel similaire en termes de fonctionnalités et de performances. Sa facilité d’utilisation en a fait l’une des solutions logicielles de montage vidéo pour non professionnel les plus populaires au monde. Dans l’ensemble, cet outil peut transformer votre ordinateur en un studio vidéo entièrement équipé où vous pouvez transformer vos vidéo en des films étonnants et stupéfiants.<br><br>Information générale:<br>•Nom du logiciel : Magix Video DeLuxe 2021 Premium<br>•Auteur : Magix Software GmbH <br>•Version : 20.0.1.73<br>•Date de parution : février 2020<br>•Compatible : Windows(64 bits) : 7/8/8.1/10",
  },
  {
    year: "02/21",
    type: "Software Bundle",
    name: "Topaz AI Bundle Suite 2021",
    weight: "10.67Go",
    version: "2021",
    pack: [
      { name: "Topaz Video Enhance AI", version: "v1.9.0" },
      { name: "Topaz Sharpen AI", version: "v2.2.3" },
      { name: "Topaz Mask AI", version: "v1.3.9" },
      { name: "Topaz Gigapixel AI", version: "v5.4.4" },
      { name: "Topaz DeNoise AI", version: "v2.4.2" },
    ],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/720648-topaz+ai+bundle+suite+2021+win+x64+en+crack",
    price: 15,
    image: "https://i.ibb.co/MGvYKkh/topazbundle.png",
    description:
      "  L'intelligence artificielle nous permet d'inventer le futur de la retouche photo. Avec l'offre groupée d'utilitaires, vous obtiendrez les outils dont vous avez besoin pour perfectionner vos images.<br><br>LISTE DES LOGICIELS INCLUS<br><br>•Topaz Video Enhance AI v1.9.0 (x64) + Crack<br>•Topaz Sharpen AI v2.2.3 (x64) + Reg<br>•Topaz Mask AI v1.3.9 (x64) + Reg<br>•Topaz Gigapixel AI v5.4.4 (x64) + Reg <br>•Topaz DeNoise AI v2.4.2 (x64) + Reg<br><br>Informations:<br>•Systeme d'exploitation :  Windows 10<br>•Architecture : 64 bits<br>•Processeur : 2 Go<br>•Memoire vive : 2 Go<br>•Disque Dur : 4 Go<br>•Résolution d'écran : 1280x800 ",
  },
  {
    name: "Adobe Master Collection CC 2020",
    type: "Software Bundle",
    weight: "36.18 GB",
    version: "v8",
    year: "07/20",
    pack: [
      {
        name: "Adobe Acrobat Pro DC",
        version: "20.9.20074",
        weight: "2.34 GB",
      },
      {
        name: "Adobe After Effects 2020",
        version: "17.1.2.37",
        weight: "2.64 GB",
      },
      {
        name: "Adobe Animate 2020",
        version: "20.5.1.31044",
        weight: "2.26 GB",
      },
      {
        name: "Adobe Audition 2020",
        version: "13.0.8.43",
        weight: "895.60 MB",
      },
      { name: "Adobe Bridge 2020", version: "10.1.1.166", weight: "935.86 MB" },
      {
        name: "Adobe Character Animator 2020",
        version: "3.3.1.6",
        weight: "1.33 GB",
      },
      { name: "Adobe Dimension", version: "3.3.0.2422", weight: "2.59 GB" },
      {
        name: "Adobe Dreamweaver 2020",
        version: "20.2.0.15263",
        weight: "1.17 GB",
      },
      { name: "Adobe Fresco", version: "1.8.0.195", weight: "412.19 MB" },
      { name: "Adobe Fuse", version: "2017.1", weight: "4.38 GB" },
      {
        name: "Adobe Illustrator 2020",
        version: "24.2.1.496",
        weight: "1.25 GB",
      },
      { name: "Adobe InCopy 2020", version: "15.1.1.103", weight: "1.40 GB" },
      { name: "Adobe InDesign 2020", version: "15.1.1.103", weight: "1.43 GB" },
      {
        name: "Adobe Lightroom Classic",
        version: "9.3.0.202005281810",
        weight: "2.15 GB",
      },
      {
        name: "Adobe Media Encoder 2020",
        version: "14.3.1.39",
        weight: "2.38 GB",
      },
      {
        name: "Adobe Photoshop 2020",
        version: "21.2.1.265",
        weight: "2.37 GB",
      },
      { name: "Adobe Prelude 2020", version: "9.0.1.64", weight: "1.29 GB" },
      { name: "Adobe Premiere Pro", version: "14.3.1.45", weight: "3.20 GB" },
      { name: "Adobe Premiere Rush", version: "1.5.20.571", weight: "1.60 GB" },
      { name: "Adobe XD", version: "31.0.12.23", weight: "223.44 MB" },
    ],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/650725-adobe+master+collection+cc+2020+v8+en-rupr%C3%A9-activ%C3%A9m0nkrus",
    price: 15,
    image: "https://i.ibb.co/0F8ttZV/6eb2f3acb2c7.png",
    description:
      "Ce pack comprend la suite Adobe Creative Cloud au complet dans sa dernière version (à dater du 23 Juillet 2020).<br><br>Configuration requise<br>•OS : Windows 7 SP1 => Windows 10<br>•RAM : 6-8 Go minimum vital recommandé (16 Go pour After Effects)<br>•Espace libre : 36.18 GB<br>•Carte graphique : 2 Go de VRAM, NVIDIA GTX 1050 ou équivalent recommandé",
  },
  {
    name: " Antidote 11",
    type: "Software",
    weight: "1.74 Go",
    version: "1.1",
    year: "12/21",
    pack: [],
    link: "	",
    price: 15,
    image: "https://static.cachem.fr/uploads/2021/10/antidote11.jpg",
    description:
      "En un instant, le correcteur analyse l’ensemble de votre texte puis vous soumet ses détections, tant pour  corriger les erreurs que pour améliorer le style. Pointez sur un mot souligné et l’infobulle vous présente  des explications, la correction requise ou une proposition de remplacement. Approuvez, et le texte se substitue  automatiquement.    En plus de corriger l’orthographe et la grammaire, vous pouvez aussi rectifier la typographie, éliminer les  répétitions et remplacer les termes non inclusifs grâce aux filtres intelligents. Jamais un logiciel ne vous  a offert autant de puissance pour épurer vos textes. <br><br>•Éditeur: Druide<br>• Système d'exploitation : Windows 11, 64 bits.",
  },
  {
    name: "Autodesk Revit",
    type: "Software",
    weight: "15.5 Go",
    version: "v2022.1.1",
    year: "11/21",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/823990-autodesk+revit+v2022+1+1+fr+win+x64+crack",
    price: 15,
    image: "https://i.ibb.co/fH5spgX/autodesk-revit-2022.jpg",
    description:
      " Revit est un logiciel de conception de bâtiment édité par la société américaine Autodesk qui permet de créer un modèle en 3D d'un bâtiment pour créer divers documents nécessaires à sa construction. <br><br>Configuration: <br>•Système d'exploitation : Windows 10<br>•Architecture : 64 bits<br>•Processeur : 2 Go Intel 6eme génération, AMD Ryzen série 1000, GPU 2Go<br>•Mémoire vive : 1 Go<br>•Disque Dur : 2 Go espace disque",
  },
  {
    name: "Le Petit Larousse 2010 Illustré",
    type: "Software",
    weight: "627 Mo",
    version: "Version 1.3.0.0",
    year: "2012",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/822942-le+petit+larousse+2010+illustr%C3%A9+version+1+3+0+0+larousse+fr+iso",
    price: 15,
    image: "https://images-na.ssl-images-amazon.com/images/I/41FGpQudi7L.jpg",
    description:
      "•Genre:   Dictionnaire électronique<br>•Auteur: Collectif Larousse<br>•Éditeur:  Larousse<br>•Format:Fichier ISO  <br>•Version: 1.3.0.0<br>•Langue: Français<br>•Langues audio:  Français<br>•Textes:  Français<br>•Sortie et publié le:   16/11/2009<br>•Plateforme:   Windows XP; Vista; 7; 8; 8.1; 10",
  },
  {
    name: "VMware Workstation Pro",
    type: "Software",
    weight: "",
    version: "615 Mo ",
    year: "11/21",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/822074-vmware+workstation+pro+v16+2+1+pro+x64+incl+keys+win+en+x64",
    price: 15,
    image: "",
    description:
      "VMware Workstation propose une outil de virtualisation de système d'exploitation (OS) sur une machine hôte. L'application  s'appelle ici un hyperviseur et peut créer des machines virtuelles (VM) complètes avec gestion du son, de la vidéo, du réseau,  de la quantité de RAM, des disques durs, des processeurs, etc. VMware Workstation peut intercepter des périphériques USB lors  de leur connexion pour les intégrer à l'OS invité. Le logiciel autorise de lancer plusieurs VM simultanément, les mettre en  pause pour les reprendre plus tard dans l'état laissé précédemment, etc. Enfin, VMware Workstation met à disposition des  utilisateurs une connexion VNC pour l'accès au bureau à distance du système invité et faciliter ainsi les démonstrations  logicielles sur un OS  propre.  ",
  },
  {
    name: "Mathworks Matlab",
    type: "Software",
    weight: "20.7 Go",
    version: "R2020B",
    year: "07/20",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/666158-mathworks+matlab+r2020b+9+9+windows+x64+en+crack",
    price: 15,
    image: "",
    description:
      "MATLAB (matrice de laboratoire) est un environnement informatique numérique  multi-paradigmes et un langage de programmation propriétaire  développé par MathWorks. MATLAB permet les manipulations matricielles, le traçage  de fonctions et de données, l'implémentation d'algorithmes,  la création d'interfaces utilisateur et l'interface avec des programmes  écrits dans d'autres langages, notamment C, C ++, C #, Java, Fortran  et Python.Bien que MATLAB soit principalement destiné à l'informatique  numérique, une boîte à outils optionnelle utilise le moteur symbolique  MuPAD,  permettant d'accéder aux capacités de l'informatique symbolique. Un package supplémentaire, Simulink, ajoute une simulation  graphique  multi-domaines et une conception basée sur un modèle pour les systèmes dynamiques et  intégrés.En 2018, MATLAB comptait plus de 3  millions d'utilisateurs dans le monde.Les utilisateurs de MATLAB  proviennent de divers horizons  en ingénierie, sciences et économie.<br><br>Configuration Recommandé<br>•OS : windows 7/8/8.1/10 64bit seulement,<br>•Processeur : i5 64 bit ou plus,<br>•Mémoire vive : 4 Go de mémoire vive,<br>•Espace disque : 30 Go,<br>•Langue: Anglais",
  },
  {
    name: "Maplesoft Maple",
    type: "Software",
    weight: "1.58 Go",
    version: "2018.0",
    year: "2018",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/260269-maplesoft+maple+2018+0+x64",
    price: 15,
    image:
      "https://allpcworld.com/wp-content/uploads/2018/09/Download-Maplesoft-Maple-2018-Free.jpg",
    description:
      "Maple est un logiciel de mathématiques qui combine le moteur mathématique le plus puissant du monde avec une interface qui le rend extrêmement   facile à analyser, explorer, visualiser et résoudre des problèmes   mathématiques.<br><br>Résolvez des problèmes de maths facilement et avec précision , sans vous   soucier du fait que vous avez perdu un signe moins quelque part  Résolvez rapidement les problèmes de maths que vous ne pourriez jamais   faire à la main (ou que vous ne voudriez pas faire à la main parce que   la vie est trop courte!)<br><br>Résoudre des problèmes de n'importe quelle branche mathématique ou   mathématique, comme le calcul, l'algèbre, les équations différentielles,   les statistiques, le contrôle, l'algèbre linéaire, la physique,   l'optimisation, la théorie des groupes, la géométrie différentielle,   le traitement du signal , modélisation financière, etc. etc.    <br><br>Obtenez un aperçu de votre problème, de votre solution, de vos données   ou de votre concept en utilisant une grande variété de tracés et   d'animations 2D et 3D personnalisables<br><br>Conservez les problèmes, les solutions, les visualisations et les   explications dans un document unique et facile à suivre , pour ne pas   perdre de temps à reconstruire vos processus de pensée    <br><br>Développer des solutions complexes en utilisant un langage de programmation sophistiqué conçu pour les mathématiques , afin que votre   code soit plus court, plus facile à écrire, plus facile à déboguer et   plus facile à maintenir<br><br>Créez des applications interactives pour vous-même, vos étudiants ou   vos collègues, sans avoir à être un programmeur expert, et partagez-les   sur le Web",
  },
  {
    name: "ACDSEE PHOTO STUDIO ULTIMATE 2022",
    type: "Software",
    weight: "250 Mo",
    version: "15.0.0.2801",
    year: "10/21",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/815597-acdsee+photo+studio+ultimate+2022+v15+0+0+build+2801+x64+fr+patch",
    price: 15,
    image: "https://i.postimg.cc/zfdk3YXs/Photo-Studio-Ultimate-2022.png",
    description:
      "Avec l'explosion de la photographie numérique, n'avons-nous pas tous besoin d'une arme secrète ? Design compact et efficace, adapté aussi bien au photographe débutant qu'au photographe expérimenté !ACDSee Ultimate 2022 brise les chaînes de la répétition et combat les agents de la fadeur en ouvrant un monde où règne le contrôle créatif et des possibilités infinies <br> Ultimate 2022 offre d'incroyables outils permettant de gagner du temps, tels que le tout nouveau mode Média, qui permet d'interagir avec la base de données de photos ACDSee,et le mode Personnes, un moteur d'intelligence artificielle qui place de manière transparente un nom sur un visageAjoutez une multitude de nouveaux outils de sélection à un éditeur de calques déjà robuste, et vous disposez d'une arme secrètepour construire votre empire de la photographie dans un monde numérique surpeuplé<br><br>Informations: <br>•Editeur(s) : ACD Systems<br>•Os du logiciel : Windows<br>•Compatibilité : Microsoft® Windows® 7 (SP1), Windows® 8, Windows® 8.1, Windows® 10 & Windows® 11 (éditions 64 bits uniquement)<br>•Version actuelle : 15.0.0.2801<br>•Date de sortie : 20 octobre 2021",
  },
  {
    name: "CorelDRAW Graphics Suite 2022",
    type: "",
    weight: "1,54 Go",
    version: "v24.1.0.360",
    year: "2022",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/926570-coreldraw+graphics+suite+2022+v24+1+0+360+win10+x64+multi+-+iso",
    price: 15,
    image: "https://m.media-amazon.com/images/I/31iaHAiNcnL._AC_.jpg",
    description:
      "Commencez votre parcours de conception du bon pied avec CorelDRAW® Graphics Suite 2021: une suite complète d'applications de conception professionnelle pour l'illustration vectorielle, la mise en page, la retouche de photos, et plus encore...<br><br>CONFIGURATION:<br>==============<br><br>•Système d'exploitation: Windows 10*, 64 bits, avec les dernières mises à jour<br>•Processeur: Intel Core i3/5/7/9 ou AMD Ryzen 3/5/7/9/Threadripper, EPYC<br>•Mémoire vive: 4 Go de mémoire RAM (8 Go ou plus sont recommandés)<br>•Espace disque: 4.3 Go d'espace disque disponible pour les fichiers d’installation et d’application<br>•Carte vidéo: compatible OpenCL 1.2 avec plus de 2 Go de mémoire RAM vidéo",
  },
  {
    name: "FileZilla Pro",
    type: "",
    weight: "11.7 Mo",
    version: "v3.55",
    year: "07/21",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/782603-filezilla+pro+v3+55+win+x64+multi+crack",
    price: 15,
    image: "https://i.ibb.co/R6cg0ZV/filezilla-pro.png",
    description:
      "FileZilla est déjà bien connu pour son logiciel client gratuit et open source de transfert de fichiers sur des serveurs FTP, FTPS et SFTP entre autres. FileZillaPro apporte également une solution pour les professionnels en ajoutant des serveurs de  stockage et des protocoles de connexion supplémentaires, spécialement dédiés aux professionnels : <br>WebDAV<br>Amazon S3<br>Backblaze B2 <br>Dropbox<br>Microsoft OneDrive<br>Service de stockage de fichiers Microsoft Azure<br>Service de stockage d'objets blob Microsoft Azure<br>Google Cloud Storage<br>Google Drive<br>OpenStack Swift<br>Box<br><br>CONFIGURATION:<br>==============<br>•Système d'exploitation  :  Windows 7 .8 10<br>•Architecture :  64 bits    <br>•Processeur :  2 Go Intel 6eme génération, AMD Ryzen série 1000, GPU 2Go<br>•Mémoire vive :  1 Go<br>•Disque Dur :  2 Go espace disque<br>•Résolution d'écran :  1280x800",
  },
  {
    name: "Virtual DJ",
    type: "",
    weight: "714 Mo",
    version: "Pro 2021 8.5.6156",
    year: "2020",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/687896-windows+virtual+dj+pro+2021+8+5+build+6156+crack+x64+multilfr",
    price: 15,
    image:
      "https://cn.trucnet.com/wp-content/uploads/2017/03/Virtual-DJ-Pro-Infinity-v8.2.3573-Plugins.jpg",
    description:
      "VirtualDJ Pro est une console Virtual DJ pratique offrant une variété de fonctionnalités pour accueillir les soirées karaoké, mélanger des chansons et bien plus de plaisir.    Le Virtual DJ est une puissante console DJ pour mixer les chansons et offre une solution pratique pour organiser des soirées karaoké de manière intuitive. Il fournit un ensemble avancé d’outils avec une variété de fonctionnalités telles que le mixage audio, les listes de lecture, le karaoké et bien d’autres. Il existe différents paramètres personnalisés et divers modules qui permettent aux utilisateurs d’obtenir un contrôle complet sur le mixage audio.",
  },
  {
    name: "Ableton.Live.Suite",
    type: "",
    weight: "2.24Go",
    version: "v11.0.0",
    year: "02/21",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/727387-ableton+live+suite+11+0+0+win+x64+-+multi+-+patch+keygen+r2r+-+sn4il",
    price: 15,
    image: "https://i.ytimg.com/vi/zAisG2rrH_Q/maxresdefault.jpg",
    description:
      "Ableton Live 11 Lite est un logiciel très léger et flexible qui rend la création et la performance musicale rapide et fluide. Il inclut des workflows, des instruments et des effets indispensables pour créer de nouveaux sons, enregistrer des idées, se produire sur scène, et bien plus encore.<br><br>CONFIGURATION:<br>==============<br>• Windows 10 (Build 1909 minimum)<br>• Intel Core i5 ou AMD équivalent<br>• 8 Go de RAM<br>• Résolution d'affichage 1366x768",
  },
  {
    name: "Guitar Pro 7 + SoundBanks",
    type: "",
    weight: "953 Mo",
    version: "v7.5.0.1322",
    year: "07/18",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/266674-windows+guitar+pro+7+v7+5+0+1322+fr+incl+soundbanks+pr%C3%A9-activ%C3%A9",
    price: 15,
    image:
      "https://nsm09.casimages.com/img/2018/06/20//18062001011920942815769709.jpg",
    description:
      "Guitar Pro est un logiciel disponible sur Windows et Mac OS qui permet à tous les musiciens de lire, d'écrire et de partager leurs tablatures",
  },
  {
    name: "Pack 123 097 GUITAR PRO TABS",
    type: "",
    weight: "3.06Go	",
    version: "1",
    year: "03/20",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/586678-repack+pack+de+123+000+tablatures+pour+guitar+pro",
    price: 15,
    image:
      "https://assets.guitar-pro.com/1.4/images/www/guitar-pro-7-features/guitar-pro-7-split-merge-staves-fr.jpg",
    description:
      "plus de 123.000 de tous les genres, pour tous les niveaux..... une vraie caverne  d' Ali Baba !",
  },
  {
    name: "	FL Studio SuperPack",
    type: "",
    weight: "5.11Go",
    version: "20.8.3",
    year: "03/21",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/932290-fl+studio+superpack+2022+9+-+nombreux+vst+-+installateur+-+freng+-+win+10+x64+-+r2r+vr+air+ce",
    price: 15,
    image: "https://i.imgur.com/lb4jwMM.jpeg",
    description:
      "  FL Studio 20.8.3.2304 All Plugins Edition<br>• Samples extraits du VSTi Battery 4<br>•Listes FL des VST préconfigurées   <br>•Tritik.Krush.PRO.v1.1.1<br>•ColdFire 1.0.0.41<br>•Xfer Serum v1.35b1<br>•FabFilter.Total.Bundle.v2022.2<br>•MeldaProduction.MCompleteBundle.v16 <br>•Ohmforce.Bundle.2016<br>•ValhallaDSP.bundle.2022.8 <br>•iZotope Ozone Advanced v9.11.1<br>• Kombinat 3.1<br>•LameVST<br>•Psyscope<br>•ANA 2 v2.0.99 Ultra Bundle + presets Vol 1-9<br>•Kick 2 v1.1.4 + presets Vol 1-8     <br>•Voxengo bundle 2022.1<br>• Evade 1.0.2<br>•MixChecker Pro v1.1.1<br>•Thermal v1.0.2<br>•PORTAL_1.0.1<br>• FilterBank_3.4<br>•Tritik.Moodal.v1.1.6 <br>•Tritik.tkDelay.v1.4.6",
  },
  {
    name: "Steinberg Cubase 12",
    type: "",
    weight: "1.29Go	",
    version: "v12.0.40",
    year: "2022",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/924884-steinberg+cubase+v12+0+40+crack+inclus+win+-+french+2022+-r2r",
    price: 15,
    image: "https://www.zupimages.net/viewer.php?id=22/33/2q2y.jpg",
    description:
      "Vous souhaitez commencer à faire votre propre musique, élever vos productions à un niveau professionnel ou optimiser votre processus de travail pour gagner en efficacité ? Quelles que soient vos intentions, Cubase vous aide à exploiter tout votre potentiel créatif. Du compositeur de musique de film hollywoodien au débutant passionné en passant par le producteur de hits planétaires, le monde de la production musicale fait confiance aux fonctionnalités complètes, aux outils efficaces et au son imbattable de notre fameux logiciel de production musicale.<br><br>INFORMATION:<br>•Publié le : 08/2022<br>•Editeur : Steinberg<br>•Compatible :Windows 10 64 bits version 21H2 (ou supérieure), Windows 11 64 bits version 21H2 (ou supérieure)<br>•Intel® Core™ i5 (mi-2013 ou postérieur) 4 cœurs minimum<br>•8 Gb de RAM minimum<br>•Cette version du logiciel n'est pas compatible avec les plugins 32 bits.",
  },
  {
    name: "Cubase pro 11",
    type: "",
    weight: "1.05Go",
    version: "11 Pro",
    year: "2020",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/798358-cubase+pro+11+multi+windows+10+x64+crack",
    price: 15,
    image: "https://www.zupimages.net/viewer.php?id=21/36/dqvd.jpg",
    description:
      "Cubase est l'un des progiciels de création musicale les plus puissants au  monde. Avec sa gamme inégalée d’outils flexibles, vous pouvez créer  n’importe quel type de musique rapidement et intuitivement.   Il est livré avec une large gamme d'instruments virtuels, d'effets et de milliers de sons.   Que vous soyez un compositeur professionnel ou un débutant en production  musicale, Cubase vous fournit tout ce dont vous avez besoin pour  transformer vos idées en musique.  ",
  },
  {
    name: "	Spotify Windows + BlockTheSpot",
    type: "",
    weight: "82.70Mo	",
    version: "2020.10.16.24",
    year: "2020",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/694891-spotify+windows+blockthespot-2020+10+16+24",
    price: 15,
    image: "",
    description:
      "  Spotify  est un service suédois de streaming musical sous la forme d'un logiciel propriétaire et d'un site web. Cette plateforme de distribution numérique permet une écoute quasi instantanée de fichiers musicaux. Le catalogue peut être parcouru par artiste ou par album, et également grâce à une fonctionnalité de liste de lecture personnalisée.L'application est disponible pour Windows, MacOS, certaines distributions Linux, iOS, Android, PlayStation 3, 4 et 5, Xbox One et Xbox series X,S ainsi que dans la plupart des navigateurs web.  D'autres objets connectés permettent également d'utiliser l'application (enceintes, télévisions, montres intelligentes, assistants vocaux...).",
  },
  {
    name: "ADOBE Indesign",
    type: "",
    weight: "1.12Go",
    version: "v17.2.1.105",
    year: "2022",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/895481-adobe+indesign+2022+v17+2+1+105+win+x64+multi+pr%C3%A9activ%C3%A9",
    price: 2000,
    image: "https://imagizer.imageshack.com/v2/640x480q90/924/YH8zbi.png",
    description:
      "Adobe InDesign est un logiciel de PAO produit par Adobe Systems. Initialement conçu pour créer des œuvres telles que des affiches, dépliants, brochures, magazines, journaux ou livres, il permet également de publier plusieurs types de contenus adaptés aux tablettes lorsque utilisé avec Adobe DPS. Les principaux utilisateurs de ce logiciel sont les graphistes et les artistes professionnels qui créent et font la mise en page de périodiques, d'affiches et d'autres produits destinés à l'impression. Il prend également en charge l'exportation des formats de livres numériques EPUB et SWF ainsi d'autres formats numériques tels que des magazines et divers produits adaptés à la consultation sur tablette tactile. En outre, InDesign prend en charge le format XML, les feuilles de style et d'autres langages de programmation, ce qui permet de l'utiliser pour exporter du texte balisé pour l'utilisation d'autres formats numériques. Le logiciel de traitement de texte Adobe InCopy utilise le même système de mise en forme qu'InDesign.<br><br>Informations:<br>• Editeur: Adobe <br> •Système d'exploitation: Windows 10 (ou plus)<br>•Version: v17.2.1.105 <br>•Langue: Multi (Français)<br><br>CONFIGURATION:<br>==============<br>•Système d'exploitation  : Windows 10 version 1803<br>•Architecture :  64 bits    <br>•Processeur :  Intel 6eme génération, AMD Ryzen série 1000, GPU 2Go<br>•Mémoire vive :  4 Go<br>•Disque Dur :  30Go espace disque<br>•Carte Graphique :  4 Go<br>•Résolution d'écran :  1280x800 ",
  },
  {
    name: "	ADOBE ILLUSTRATOR",
    type: "",
    weight: "1.81Go	",
    version: "v26.3.1.1103",
    year: "2022",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/895122-adobe+illustrator+2022+v26+3+1+1103+win+x64+multi+pr%C3%A9activ%C3%A9",
    price: 2000,
    image: "https://i.imgur.com/hFf93eI.png",
    description:
      "Adobe Illustrator est un logiciel de création graphique vectorielle. Il fait partie de la gamme Adobe, peut être utilisé indépendamment ou en complément de Photoshop, et offre des outils de dessin vectoriel puissants. Les images vectorielles sont constituées de courbes générées par des formules mathématiques. L'un des outils principaux d'Illustrator étant « la plume » qui permet de tracer des courbes à l'aspect parfait grâce au placement de points d'ancrage et de tangentes qui vont en modifier la courbure. Un des avantages des images vectorielles est qu'elles sont indépendantes de la résolution, c’est-à-dire qu'elles ne perdent pas en qualité lorsqu'on les agrandit. Adapté aussi bien à la création de document papier qu'à celle d'illustrations pour Internet (logos, affiches, etc.) ce logiciel est orienté vers le marché professionnel, il intègre de nombreuses options propres à améliorer la productivité.<br><br>Informations:<br>• Editeur: Adobe<br>•Système d'exploitation: Windows 10 (ou plus)<br>•Version : 26.3.1.1103<br><br>CONFIGURATION:<br>==============<br>•Système d'exploitation  : Windows 10 version 1803<br>•Architecture :  64 bits    <br>•Processeur :  Intel 6eme génération, AMD Ryzen série 1000, GPU 2Go<br>•Mémoire vive :  4 Go<br>•Disque Dur :  30Go espace disque<br>•Carte Graphique :  4 Go<br>•Résolution d'écran :  1280x800 ",
  },
  {
    name: "	Autodesk 3ds Max",
    type: "",
    weight: "3.82Go",
    version: "2020",
    year: "11/2019",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/851696-autodesk+3ds+max+2020+win+multi+crack",
    price: 7000,
    image: "https://www.zupimages.net/viewer.php?id=22/04/b4wt.jpg",
    description:
      "Le logiciel Autodesk 3ds Max 2020 produit une animation, un rendu et une modélisation 3D de qualité professionnelle. Un ensemble d'outils efficaces et flexibles pour vous aider à créer un meilleur contenu 3D en moins de temps.Avec 3ds Max, vous pouvez concevoir, créer le modèle d'animation 3D le plus populaire et le plus utilisé au monde, vous permettant de créer des scènes très réalistes. Grâce à la possibilité de personnaliser, de raccourcis et d'un fonctionnement flexible, vous pouvez créer du contenu 3D rapidement et efficacement avec 3DS Max.",
  },
  {
    name: "Lumion Pro",
    type: "",
    weight: "18.60Go",
    version: "11.0.1.9",
    year: "2020",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/742976-win+lumion+pro+11+0+1+9+x64+multi+tpc",
    price: 2000,
    image: "https://i.ibb.co/xDDF5F9/Lumion-11-version-Pro.png",
    description:
      "Lumion est un logiciel de rendus 3D et de visualisation en Temps Réel adapté à tous les professionnels de la conception architecturale et technique : Architectes, Paysagistes, Aménageurs, Collectivités, Urbanistes...Adapté aux grands projets architecturaux et d’aménagements urbains, Lumion vous permet de naviguer en Temps Réel dans votre projet, de simuler l’environnement avec un réalisme époustouflant. Créez des images, des vidéos, des panoramas 360° et des VR en toute simplicité, à partir des modèles numériques 3D issus de vos logiciels de conception. Grâce à Lumion, la 3D Temps Réel révolutionne les modes de communication et de visualisation. La navigation est intuitive et les temps de calcul des rendus sont largement améliorés pour créer des images et des vidéos d’une grande qualité.",
  },
  {
    name: "Chief Architect X12 + SSA Catalogs",
    type: "",
    weight: "7.63Go",
    version: "02.2020",
    year: "02.2020",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/594065-chief+architect+x12+ssa+catalogs+windows+x64+en+crack",
    price: 7000,
    image:
      "https://lzd-img-global.slatic.net/g/p/b230e5b8897e825f74e6c1facfe82b19.jpg_720x720q80.jpg_.webp",
    description:
      "Le logiciel Chief Architect donne vie aux projets de conception de maison. Les outils de construction automatisés pour la conception de maison, la décoration intérieure et la conception de cuisines et de salles de bain facilitent la création des dessins de construction, d'élévations, de détails CAO et de modèles 3D.<br><br>Information: <br>•Éditeur : Chief Architect (TM)<br>•Système d'exploitation : Windows 7 / 8 / 8.1 / 10 (64 bits uniquement)<br>•Date : 03/2020<br>•Version : 22.1.1.1 (X12)<br>•Langue: Anglais<br>•Taille totale : 7.63 Go",
  },
  {
    name: "Adobe Dreamweaver",
    type: "",
    weight: "1.01Go",
    version: "v20.0.0.15196",
    year: "2020",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/517057-adobe+dreamweaver+2020+v20+0+0+15196+win+x64+multi+pr%C3%89-activ%C3%89",
    price: 2000,
    image:
      "https://i1.wp.com/fileriver.net/wp-content/uploads/2019/10/dreamviewer-crack.png",
    description:
      "Avec Adobe Dreamweaver CC 2020, vous pouvez facilement créer, coder et gérer des sites Web dynamiques avec un moteur de codage intelligent et simplifié. Conseils de code d'accès pour apprendre et modifier rapidement les standards HTML, CSS et autres normes Web. Et utilisez des aides visuelles pour réduire les erreurs et accélérer le développement du site.Grâce à Adobe Dreamweaver CC, vos sites sont plus rapidement opérationnels grâce à des modèles de départ que vous pouvez personnaliser pour créer des e-mails HTML, des pages À propos des pages, des blogs, des pages de commerce électronique, des newsletters et des portefeuilles. La coloration du code et les conseils visuels vous aident à lire le code plus facilement pour des éditions et des mises à jour rapides.Dreamweaver s’intègre désormais à la dernière version de Chromium Embedded Framework. Vous pouvez ainsi créer un site Web HTML5 moderne, afficher des éléments, des grilles CSS, etc. La collaboration est facile avec le support Git. Gérez tout votre code source dans Dreamweaver et effectuez toutes les opérations courantes  directement à partir du panneau Git.<br><br>Informations: <br>•Processeur: Intel® Core 2 ou AMD Athlon® 64, 2 GHz ou plus rapide <br>•Compatible: Windows 10 avec la mise à jour version 1607 ou version ultérieure.<br>•RAM : 2 Go de RAM (4 Go recommandés)<br>•Espace Disque : 2 Go d’espace disque disponible pour l’installation<br>•Résolution du moniteur: Affichage de 1280 x 1024<br>•Graphique : carte vidéo 16 bit ",
  },
  {
    name: "Zbrush",
    type: "",
    weight: "	1.61Go",
    version: "2020.1",
    year: "2020",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/562745-zbrush+2020+1+multi+fr+win+64bits+crack+updater",
    price: 4000,
    image:
      "https://www.zbrushcentral.com/uploads/default/original/4X/b/9/2/b92a3632ac319a409f8e7ec7e42aff2b989915cb.jpeg",
    description:
      "ZBrush établit la norme de l'industrie pour la sculpture numérique. Ses  fonctionnalités vous permettent d'utiliser des pinceaux personnalisables   pour façonner, texturer et peindre de l'argile virtuelle dans un  environnement en temps réel. Lorsque vous utilisez ZBrush, vous utilisez   les mêmes outils que ceux utilisés par les studios de cinéma, les  concepteurs de jeux, les fabricants de jouets / objets de collection,  les créateurs de bijoux, les concepteurs du secteur de l’aviation /  automobile, les illustrateurs et les artistes du monde entier.  ZBrush 2020 continue sur la voie de la créativité et de la productivité avec  de nouvelles fonctionnalités majeures permettant aux artistes de  travailler encore plus rapidement, en se concentrant plus  particulièrement sur la création de formes de surfaces dures et de  formes mécaniques avec une plus grande facilité. Tout en travaillant ou  en finale lors de la création, vous serez en mesure de produire un rendu   non réaliste époustouflant avec un retour instantané. ZBrush 2020 vous  aide également à être plus efficace avec son nouveau système  d'organisation des dossiers, son outil de rétopologie automatique  réécrit et un nouveau système de caméra. Votre art changera pour  toujours",
  },
  {
    name: "WYSIWYG Web Builder",
    type: "",
    weight: "43.08Mo	",
    version: "17.1.4",
    year: "03/2022",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/867034-wysiwyg+web+builder+17+1+4-anglaisfran%C3%A7ais-win-x64-crack",
    price: 3000,
    image: "",
    description:
      "Pour faire son propre site web il y a encore quelques années le passage quasi obligé était l'apprentissage du HTML.  Aujourd'hui une large offre logicielle s'occupe de vous affranchir de cette  connaissance. Que l'on parle de FrontPage, de Dreamweaver etc. tous sont conçu  dans le but d'obtenir plus facilement un site web qu'en apprenant le  HTML. WYSIWYG Web Builder vous aide donc à éditer un site web grâce à la méthode du WYSIWYG (What-You-See-Is-What-You-Get / Ce que vous voyez  est ce que vous obtenez).<br><br>INFORMATIONS: <br>•Nom : WYSIWYG Web Builder<br>•Editeur :  WYSIWYG         <br>•Publié le : 06/03/2022      <br>•Version : 17.1.4<br>•Compatible : Windows 7 8 10 11 ",
  },
  {
    name: "HFS+.for.Windows.by.Paragon.Software",
    type: "",
    weight: "43.91Mo",
    version: "v11.4.273",
    year: "",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/842861-hfs+for+windows+by+paragon+software+v11+4+273+multi-windows",
    price: 4000,
    image: "https://i.imgur.com/N93lKN0.png",
    description:
      "Si vous travaillez sur un ordinateur Windows et avez besoin d’écrire ou de lire des fichiers issus d’une clé USB, d’un disque dur ou d’un SSD formaté sous macOS, il vous faut HFS+ for Windows by Paragon Software.",
  },
  {
    name: "Labcenter Proteus Professional",
    type: "",
    weight: "446 Mo",
    version: "8.13 SP0 Build 31525",
    year: " 2021",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/821662-labcenter+proteus+professional+8+13+sp0+build+31525+pr%C3%A9-crack%C3%A9windows",
    price: 10000,
    image: "https://www.zupimages.net/up/21/45/ifpq.jpg",
    description:
      "Proteus est une suite logicielle permettant la CAO électronique éditée par la société Labcenter Electronics. Proteus est composé de deux logiciels principaux : ISIS, permettant entre autres la création de schémas et la simulation électrique, et ARES, dédié à la création de circuits imprimés.Grâce à des modules additionnels, ISIS est également capable de simuler le comportement d'un microcontrôleur (PIC, Atmel, 8051, ARM, HC11...) et son interaction avec les composants qui l'entourent.  ",
  },
  {
    name: "WinRelais",
    type: "",
    weight: "65.5 Mo",
    version: "2.2 Expert",
    year: "2017",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/804089-winrelais+v2+2+expert+windows+fr+crack",
    price: 6000,
    image: "",
    description:
      "WinRelais™ est un logiciel de saisie de schémas électrotechniques de types unifilaires, multifilaires, architecturaux et développés, pour le bâtiment et l’industrie. Il permet aussi de dessiner des grafcets ainsi que des schémas pneumatiques et hydrauliques.",
  },
  {
    name: "Fritzing",
    type: "",
    weight: "212.21Mo",
    version: "0.9.3b x64",
    year: "2016",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/924469-fritzing+0+9+3b+win+x64+multi+portable",
    price: 15,
    image:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Fritzing_logo_(new).png/1280px-Fritzing_logo_(new).png",
    description:
      "Fritzing est une initiative open source pour le hardware qui rend l'électronique accessible à tous en tant que matériau créatif. Nous proposons un outil logiciel, un site Web communautaire et des services dans l'esprit de Processing et Arduino, favorisant un écosystème créatif qui permet aux utilisateurs de documenter leurs prototypes, de les partager avec d'autres, d'enseigner l'électronique dans une salle de classe, et de concevoir et fabriquer des PCB professionnels.<br><br>INFORMATIONS:<br>•Nom du Programme : Fritzing<br>•Éditeur : Fritzing GmbH<br>•Plateforme : Windows  OS<br>•compatible : Windows 11/10/8.1/8/7/Vista/XP x64<br>• Version : 0.9.3b <br>•Date du logiciel : 2 juin 2016  ",
  },
  {
    name: "Rosetta Stone",
    type: "",
    weight: "100 Mo",
    version: "5.0.37",
    year: "2015",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/77005-rosetta+stone+5+0+37+cours+multi+langue+windows",
    price: 2500,
    image:
      "https://www.staples-3p.com/s7/is/image/Staples/s0459466_sc7?$splssku$",
    description:
      "Pour qui est fait la version logicielle de 'Rosetta Stone' ?Si vous souhaitez apprendre à votre rythme votre nouvelle langue,de manière autonome sur votre ordinateur, c'est parfait pour vous !Si vous souhaitez améliorer votre prononciation, mais que dans un premier temps vous n'avez pas besoin de tuteur natif ou bien d'application mobile.Vous pouvez bien sur à tout moment souscrire en plus pour les versions en ligne)<br><br>INFORMATIONS:<br>•Editeur(s) : Rosetta Stone<br>•Os du logiciel : Windows<br>•Compatibilité  : XP / 7 / 8 / 10<br>•Version : v5.0.37<br>•Date de sortie :  2015",
  },
  {
    name: "Synthesia",
    type: "",
    weight: "50.20 Mo",
    version: "10.6.5311",
    year: "2019",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/577515-synthesia+10+6+5311+-+windows+x86x64+-+fr+-+crack+-+p2p",
    price: 3000,
    image:
      "https://images.weserv.nl/?url=https://www.01net.com/images/logiciel/44476b.jpg",
    description:
      "Synthesia est un jeu qui va vous permettre d'apprendre à jouer du piano tout en vous amusant. Vous devez simplement suivre et jouer en rythme en appuyant sur les touches affichées à l'écran. Au début des leçons vous aurez le choix entre 4 chansons, mais au fur et à mesure de vos réussites, d'autres chansons à jouer se débloqueront et vous pourrez ainsi augmenter votre niveau.<br><br>INFORMATIONS:<br>•Publié le : 30.09.2019<br>•Editeur : Nicholas Piegdon<br>•Version : 10.6.5311<br>•Compatible : windows 7 et ultérieurs<br>•Taille : 50.2 mo<br>•Licence : dans le dossier",
  },
  {
    name: "LE SPHINX PLUS",
    type: "",
    weight: "53.76Mo",
    version: "V5",
    year: "2018",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/362991-win+le+sphinx+plus+v5+2018+fr+portable",
    price: 3000,
    image: "",
    description:
      "Sphinx Plus² est un logiciel pour Windows vous permettant de créer des questionnaires en enquêtes de satisfactions. Il est disponible dans sa version d'évaluation et de démonstration.  Vous pourrez ainsi créer un nombre illimité de questionnaires et créer toutes les questions qui vont avec. Les choix sont à cet effet multiples et vous pourrez créer des ouvertes ou fermées. Les libellées et titres sont bien évidemment modifiables et personnalisables à n'importe quel moment. Notez qu'une interface d'analyse statistique des résultats est proposée pour observer et consigner les réponses et les analyser en quelques clics !",
  },
  {
    name: "IBM SPSS STATISTICS",
    type: "",
    weight: " 1,74 Go",
    version: "v26.0",
    year: "",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/642929-ibm+spss+statistics+v26+0+x64+x86+fr+win",
    price: 4000,
    image:
      "https://images.weserv.nl/?url=https://images-na.ssl-images-amazon.com/images/I/41UZEV9pvUL._AC_.jpg",
    description:
      "IBM® SPSS® Statistics est le premier logiciel statistique au monde utilisé pour résoudre les problèmes commerciaux et de recherche au moyen d'analyses ad hoc, de tests d'hypothèses et d'analyses prédictives. Les organisations utilisent IBM SPSS Statistics pour comprendre les données, analyser les tendances, prévoir et planifier pour valider les hypothèses et tirer des conclusions précises. <br><br>VERSION:v26 ",
  },
  {
    name: "Visual Studio Professionel 2022",
    type: "",
    weight: "34,3 Go",
    version: "17.3.0 Preview 1.1",
    year: "2022",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/904153-microsoft+visual+studio+2022+pro+win+x64+fr+-+iso",
    price: 6000,
    image: "",
    description:
      "Visual Studio 2022 est le meilleur Visual Studio jamais crée. Notre premier IDE 64 bits facilite l’utilisation de projets encore plus volumineux et de charges de travail plus complexes.Le contenu que vous effectuez tous les jours, comme taper du code et changer de branche, semble plus fluide et plus réactif. Et les erreurs de mémoire? Ils sont sur le point d’être une mémoire distante.Nom : Visual Studio Professionel 2022 <br><br>INFORMATION: <br>•Editeur : Microsoft<br>•Publié en : 2022 <br>•Version :  17.3.0 Preview 1.1  <br>•Avec Visual Studio, vous pouvez écrire en C/C++, C#, F#, Visual Basic, Razor, HTML5, CSS, Javascript, Typescript, XAML et XML",
  },
  {
    name: "RAPID CSS EDITOR",
    type: "",
    weight: "48.04Mo",
    version: "15.3.0.205",
    year: "2018",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/304449-windows+rapid+css+editor+2018+15+3+0+205+crack+multilingue",
    price: 2000,
    image: "https://i.imgur.com/owEt05p.png",
    description:
      "Principales fonctionnalités:<br> •Création : Rapid CSS Editor possède une interface de création divisée en plusieurs fenêtres. Il permet d'afficher l'état du projet au fur et à mesure de son avancement. Il contient également des modèles pouvant être choisis par l'utilisateur pour éviter de saisir entièrement le code.  <br>  •Modification : ce logiciel peut modifier directement l'apparence d'une page web en retouchant son code CSS. Il est possible de basculer d'un modèle à un autre tout en gardant le contexte primaire de la page. Il colore les codes syntaxiques du langage pour aider l'utilisateur pendant l'édition.<br> •Sauvegarde : les fichiers traités avec Rapid CSS Editor sont sauvegardés dans le format CSS. Ils peuvent servir dans la conception d'autres pages web sans avoir besoin de les retoucher. Ces fichiers sont supportés par tous les éditeurs CSS.  ",
  },
  {
    name: "Navicat Premium",
    type: "",
    weight: "83.2 Mo",
    version: "15.0.5",
    year: "2019",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/545243-navicat+premium+15+0+5+anglais+crack+win+x64",
    price: 4500,
    image:
      "https://image.noelshack.com/fichiers/2019/52/7/1577623728-image.jpg",
    description:
      "Navicat Premium est un outil de développement de bases de données qui vous permet de vous connecter simultanément à des bases de données MySQL, MariaDB, MongoDB, SQL Server, Oracle, PostgreSQL et SQLite à partir d'une seule application. Il est compatible avec des bases de données du Cloud telles Amazon RDS, Amazon Aurora, Amazon Redshift, Microsoft Azure, Oracle Cloud, Google Cloud et MongoDB Atlas. Vous pouvez rapidement et facilement construire, gérer et maintenir vos bases de données.  ",
  },
  {
    name: "	JetBrains IntelliJ IDEA",
    type: "",
    weight: "562.45Mo	",
    version: "2019.1.2",
    year: "2019",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/479262-jetbrains+intellij+idea+2019+1+2+win+en+crack",
    price: 2000,
    image:
      "https://resources.jetbrains.com/storage/products/intellij-idea/img/meta/intellij-idea_1280x800.png",
    description:
      "IntelliJ IDEA est un IDE Java commercial développé par JetBrains. Il est fréquemment appelé par le simple nom d’« IntelliJ » ou « IDEA » .    Intellij IDEA, est un IDE considéré comme l'un des plus 'intelligent' en matière de programmation Java. Sans être intrusif, la plateforme de  développement se comporte comme une seconde main pendant l'écriture des lignes de code avec un debugage instantané, une correction douce, un apprentissage de votre code en vu de tests discrets. Évidement, l'intervention de l'IDE s'effectue en fonction de vos demandes et niveaux d'intervention requis par vos soins. L'interface dispose aussi d'un outil de design pour la réalisation d'interface utilisateur, d'un système de gestion des langues, de moteur de recherche, etc. Au nombre de ses fonctionnalités, IntelliJ IDEA apporte une étroite intégration avec quelques-uns des outils de développement libres les plus répandus tels que Git, CVS, Subversion, Ant et Maven, JUnit et TestNG. Un greffon gratuit existe également pour intégrer IntelliJ IDEA à divers outils d’Atlassian : JIRA, Bamboo, Crucible et FishEye.<br><br>•Version : 2019.1.2",
  },
  {
    name: "	JetBrains PhpStorm 2020",
    type: "",
    weight: "300.06Mo	",
    version: "2020.1",
    year: "2020",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/644135-jetbrains+phpstorm+2020+1+build+201+6668+153+en+windows+activation",
    price: 2000,
    image:
      "https://pbs.twimg.com/profile_images/1206598279439495168/8FUu0Muv.jpg",
    description:
      "PhpStorm est un éditeur pour PHP, HTML, CSS et JavaScript, édité par JetBrains.  Il permet d'éditer du code PHP pour les versions allant de la 5.3 à la 7.4, l'éditeur possède :<br>•Une coloration syntaxique dynamique<br>•Des analyseurs d'erreurs syntaxiques et orthographiques (en anglais)<br>•Une auto-complétion intelligente du code en Javascript comme en PHP<br>•Des fonctionnalités de réusinage automatisé de code en Javascript comme en PHP<br><br>Outre ces caractéristiques, on peut trouver les outils suivants pré-embarqués :<br>•Le déploiement des fichiers via FTP, FTPS, SFTP, etc. avec synchronisation automatique<br>•Une interface utilisateur unifiée pour la gestion de versions, en surcouche à Git, Mercurial, Subversion et Perforce6.  Une interface utilisateur pour les logiciels de tests tels que PHPUnit<br>•Le débogage pas-à-pas et le profilage de code en dialoguant avec Xdebug.  <br><br>Il permet aussi de visualiser l'architecture de bases de données de différentes sources (MySQL, SQLite, etc.).  Enfin, il permet l'intégration d'outils d'opérations serveur comme Vagrant, Docker, une console SSH et bien d'autres outils.",
  },
  {
    name: "CoffeeCup Responsive Bootstrap Builder 2.5 Build 308",
    type: "",
    weight: "401 Mo",
    version: "2.5 Build 308",
    year: "18/10/2018",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/455868-windows+coffeecup+responsive+bootstrap+builder+2+5+build+308+pr%C3%A9+activ%C3%A9-eng+portable",
    price: 2000,
    image:
      "https://res.cloudinary.com/iblogger/image/upload/v1516163332/blackforest_ta6buy.jpg",
    description:
      "Concevoir un site Web sans coder ni savoir coder est probablement le moyen le plus pratique pour les débutants ou les concepteurs front-end. C'est ainsi que le logiciel de développement Web est pratique. CoffeeCup Software est probablement l’un des logiciels de développement Web populaires après Dreamweaver.  Le logiciel a plus que des fonctionnalités standard pour le constructeur de conception Web. Vous pouvez ajouter et supprimer des éléments et des composants tels que rangée, colonne, section, menus, accordéons, alertes, panneaux d'onglets, boîtes de dialogue modales, etc. Les autres fonctionnalités incluent des animations et des transitions, ainsi que des outils CSS permettant de créer votre propre style. Tous les composants et symboles Bootstrap sont personnalisables. Vous pouvez également importer le thème prédéfini pour commencer. Vous pouvez également avoir accès aux bibliothèques de symboles en le synchronisant automatiquement. S'agissant d'un Bootstrap Builder, les sites Web que vous créez à partir du logiciel sont réactifs ou compatibles avec les appareils mobiles, ce qui vous aidera à obtenir davantage de conversions.<br><br>•Editeur : CoffeeCup Software<br>•Publié le : 18/10/2018<br>•Version : 2.5 308<br>•Compatible : /W7/W8/W10<br>•Langue : anglais<br>•Taille totale: 401 Mo<br>•Licence : Licence Pro",
  },
  {
    name: "Sony Vegas Pro",
    type: "",
    weight: "547.64Mo",
    version: "16 build 248",
    year: "27 Aout 2018",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/502843-sony+vegas+pro+16+build+248+win+multi+crack",
    price: 4000,
    image: "https://i.ytimg.com/vi/e6v-6XGkL_4/maxresdefault.jpg",
    description:
      "Sony Vegas pro est un outil de conception vidéo modernisé. Il dispose de plusieurs contrôles de création permettant à l'utilisateur de réaliser une vidéo originale digne d'un professionnel. Facile à utiliser, Sony Vegas ne requiert aucune connaissance particulière en traitement vidéo.  Éditez des vidéos plus rapidement que jamais avec le nouveau flux de travail de storyboard dynamique unique en son genre: Supprimez automatiquement les bordures noires indésirables de votre projet, ajoutez des sous-titres d'un fichier et importez toutes vos vidéos dans la timeline en un seul clic. Grâce à l'accélération GPU, restituez vos vidéos en un temps record et terminez même les projets complexes plus rapidement. Vous êtes donc au sommet de votre jeu en matière de montage vidéo.<br><br>Configuration Requise<br>•Système d'exploitation : Microsoft® Windows 10 (64-bit)<br>•Processeur :Intel Core i5 6e génération (ou équivalent AMD) ou plus. 2,5 Ghz et 4 Core minimum. Pour 4K, Intel Core i7 7e génération (ou équivalent AMD) ou plus. 3,0 Ghz et 8 Core minimum<br>•Mémoire vive : RAM 8 Go minimum (16 Go recommandés ; 32 Go recommandés pour 4K)<br>•Mémoire du disque dur : 1,5 Go d'espace pour l'installation du programme<br>•disque SSD ou système multidisque rapide RAID pour les fichiers 4KAutre : Microsoft .NET Framework 4.0 SP1 (inclus sur le disque de l'application)",
  },
  {
    name: "MiniTool Power Data Recovery Business 11",
    type: "",
    weight: " 262Mo ",
    version: "6.5",
    year: "17/05/ 2022",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/902353-windowsminitool+power+data+recovery+business+11+x86x64+multi+fr+patch",
    price: 3000,
    image:
      "https://www.intowindows.com/wp-content/uploads/2011/01/MiniTool-Power-Data-Recovery-Free-Edition-for-Windows.jpg",
    description:
      "Récupération de données de puissance MiniTool Power Data Recovery est le moyen le  plus simple de récupérer des données à partir de n'importe quel  stockage, y compris un disque dur, un support numérique, une  récupération de CD / DVD, etc. Ce logiciel est conçu pour récupérer  toutes vos données, peu importe la perte de celles-ci par suppression  accidentelle, partitionnement, formatage, attaque de virus ou par panne  du système. MiniTool Power Data Recovery est livré avec une technologie  d'analyse approfondie avancée qui numérise et analyse automatiquement  les formats de données brutes, notamment les fichiers Microsoft Office,  les images numériques, les fichiers multimédias (mp3, film, etc.), les  documents, les fichiers (compressés), etc.    MiniTool Power Data Recovery prend en charge la récupération de données dans toutes les  situations, notamment la récupération de fichiers supprimés, la  récupération de fichiers corrompus, la récupération de fichiers à partir  de RAW et la récupération de tous les fichiers perdus. Cet outil  constitue la meilleure solution pour la récupération de données, que ce  soit par accident ou en raison d'une détérioration du système ou d'une  défaillance matérielle. Power Data Recovery 9 est livré avec une  nouvelle interface utilisateur intuitive, simple et facile à utiliser  ",
  },
  {
    name: "Claris FileMaker Pro",
    type: "",
    weight: "297 Mo",
    version: "19.5.4.401",
    year: "Septembre 2022",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/949291-filemaker+pro+19+5+4+401+win+x64+multi+key",
    price: 6000,
    image: "https://www.zupimages.net/up/21/49/ysjm.png",
    description:
      "Créez des applications comme un patron. Lancez-vous dans la transformation  numérique avec Claris FileMaker. Créez rapidement des applications  personnalisées qui résolvent les problèmes de votre entreprise  aujourd'hu et demain. Accélérez votre activité, libérez le potentiel  créatif de votre équipe et obtenez de meilleurs résultats.",
  },
  {
    name: "Microsoft SQL Server 2017 Entreprise",
    type: "",
    weight: "3.14Go	",
    version: "2017",
    year: "2017",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/504532-microsoft+sql+server+2017+entreprise+win+x64+fr",
    price: 8000,
    image: "https://nsa40.casimages.com/img/2019/09/23/190923091410592298.jpg",
    description:
      "SQL Server Enterprise 2017, propose des fonctionnalités de centre de données haut de gamme complètes pour répondre aux exigences en matière de base de données et d'aide à la décision.  Il faut télécharger après Reporting Services qui n'est plus automatiquement intégré",
  },
  {
    name: "WINDEV, WEBDEV ET WINDEV MOBILE 24 VERSION 73h",
    type: "",
    weight: "3.49Go	",
    version: "73h",
    year: "",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/538394-windev+webdev+et+windev+mobile+24+fr+pour+windows+avec+crack",
    price: 6000,
    image: "",
    description:
      "WinDev est un atelier de génie logiciel (AGL) édité par la société française PC SOFT et conçu pour développer des applications, principalement orientées données pour Windows 10, 8, 7, Vista, XP, 2008, 2003, 2000, mais également pour Mac OS, Linux, .Net et Java et en passant par toute plateforme mobile qu’elles soient Android, IOS, WindowsPhone et bien plus encore.  Il propose son propre langage, appelé le WLangage.  Info Upload  Format : EXE  Langue : Français",
  },
  {
    name: "KNX ETS pro 5.7.2",
    type: "",
    weight: "277Mo",
    version: "5.7.2",
    year: "24/04/2019",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/641948-knx+ets+pro+5+7+2+-+win+fr+crack",
    price: 5000,
    image: "https://i.ibb.co/18V5gFp/knx.jpg",
    description:
      "ETS est l'acronyme de Engineering Tool Software : un logiciel indépendant des fabricants pour concevoir et configurer des installations de contrôle de maisons et de bâtiments intelligents avec le système KNX. ETS est un logiciel qui fonctionne sur des ordinateurs équipés de Windows©.    KNX Association, en tant que fondateur et propriétaire de la norme KNX, offre avec ETS un outil de configuration qui fait de facto partie de la norme KNX et donc une partie du système KNX. Il en résulte les avantages suivants :  Garantie de compatibilité maximale du logiciel ETS avec la norme KNX,  Toutes les bases de données pour des produits certifiés de tous les fabricants KNX peuvent être importées dans ETS,  Compatibilité ascendante d'ETS à des données et des projets provenant de versions antérieures d'ETS (jusqu'à ETS2),  Partout dans le monde, tous les intégrateurs et installateurs utilisent le seul et même outil ETS pour chaque projet KNX et pour chaque appareil certifié KNX. La fiabilité de l'échange de données est donc garantie.",
  },
  {
    name: "MICROSOFT TOOLKIT V2.6.4 ACTIVATEUR OFFICE 2016 - 2019 & WINDOWS 10",
    type: "",
    weight: "56,00 Mo",
    version: "V2.6.4",
    year: "",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/316475-microsoft+toolkit+v2+6+4+activateur+office+2016+-+2019+windows+10",
    price: 2000,
    image:
      "https://4.bp.blogspot.com/-0ve4W6ZmXVg/V_Zwf4sLxdI/AAAAAAAADRw/PXbqJw4riRUwptXArX0DIvvshNT-MtVLACLcB/s1600/Microsoft-Toolkit-2.6.2-Activator-Windows-Office-2013-Full-Down.png",
    description:
      "Microsoft Toolkit - KMS-activator multifonction pour les systèmes d'exploitation Windows Vista, 7, Windows 8 / Server, 2012 et Office 2010/2013/2016/2019.  Comprend un ensemble d'outils pour gérer les licences et l'activation. Il peut utiliser le KMS activé, même si vous utilisez une licence au détail. Nous obtenons donc un seul activateur pour les produits Microsoft.  Il s'agit d'un ensemble d'outils et de fonctions pour la gestion des licences, du déploiement et de l'activation de Microsoft Office et Windows.  Toutes les sorties de ces fonctions sont affichées dans la Console d'informations.  Toutes les fonctions sont exécutées en arrière-plan et l'interface graphique est désactivée pour empêcher l'exécution de plusieurs fonctions car elles peuvent entrer en conflit ou causer des dégâts si elles s'exécutent simultanément.  Les fonctions de personnalisation de l'installation de Microsoft Office (personnaliser l'onglet Configuration) Désinstallateur AutoKMS (si AutoKMS est installé), Désinstaller AutoRearm (si AutoRearm est installé),  Office Uninstaller et Product Key Checker fonctionnent même si Microsoft Office ou Windows n'est pas installé / pris en charge.",
  },
  {
    name: "La Solution Ciel 2013",
    type: "",
    weight: "273 Mo",
    version: "19.0",
    year: "2013",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/60239-ciel+2013+19+0+la+solution+win+fr+keygen",
    price: 15,
    image: "",
    description: "",
  },
  {
    name: " SAGE 100 COMPTABILITE i7.v8.50 ",
    type: "",
    weight: "178mo",
    version: "V8.50 ",
    year: "",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/282333-windows+sage+100+comptabilite+i7+v8+50+multi+crack",
    price: 5000,
    image:
      "http://blog.arcgestion.fr/wp-content/uploads/2016/02/Generationi7_v2.jpg",
    description:
      "Toutes les fonctionnalités des logiciels decomptabilité Sage de la ligne 100 et l'essentiel pour la tva sur encaissement.  Ce logiciel comporte toutes les fonctions : budgétaire,analytique, reporting, TVA sur encaissement, rapprochement bancaire  automatique, révision comptable.  SageComptabilité 100 Pack + est la version la plus utilisée par les entreprises et  les experts comptable.  Elle assure toute la comptabilité générale,auxiliaire, analytique (sur 11 plans) et budgétaire et offre toutes les fonctions nécessaires à unetenue évoluée et structurée de la comptabilité : TVA sur les encaissements, rapprochement bancaire automatique, relance clients,lettrage en euros et devises avec équilibrage automatique et gestion des écarts  de change...  ",
  },
  {
    name: "XMIND 8 UPDATE 8",
    type: "",
    weight: "158 mo",
    version: "8 UPDATE 8 - PRO ",
    year: "",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/453946-xmind+8+update+8+-+pro+win+multi+crack",
    price: 4000,
    image: "https://i.imgur.com/GXC6Fha.jpeg",
    description:
      "Xmind est un logiciel vous permettant de créer des schémas d'organisation afin d'être plus productif.  Vous pouvez ainsi planifier plus facilement vos projets pour les terminer en temps et en heure.    Les diagrammes que vous pouvez créer sont de plusieurs types: pyramidaux, en arbres, diagrammes en arrêtes de poisson, logique sous forme parents-enfants, en tableaux à entrées multiples, diagrammes conceptuels à l'aide de bulles et flèches...    Il dispose aussi d'un type de diagramme spécial, le Mind Map, plaçant la racine au centre.    Possédant une gamme de symboles très étendues, allant des flèches simples aux étoiles à huit branches, vous pouvez ajouter des liens hypertextes et des commentaires audio.    Enfin, vous pouvez sauvegarder le tout sous la forme de présentation PowerPoint, fichier PDF, Word, RTF ou même en un set d'images JPEG, GIF, BMP ou PNG.    L'interface est entièrement paramétrable.  ",
  },
  {
    name: "SMS DELIVERER ENTERPRISE ",
    type: "",
    weight: "5,08 Mo",
    version: "2.1.2",
    year: "",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/369229-sms+deliverer+enterprise+2+1+2+eng+pre-activated-+parand+windows",
    price: 15,
    image: "",
    description:
      "SMS Deliverer Enterprise est une application logicielle compacte destinée à   aider les utilisateurs à envoyer des messages texte courts à plusieurs numéros   de téléphone.",
  },
  {
    name: "Total Commander",
    type: "",
    weight: "8.32 Mo",
    version: "10.00",
    year: "",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/773669-win+total+commander+10+00+x86x64+multi-fr+key",
    price: 1000,
    image: "https://www.zupimages.net/up/21/24/i6pc.png",
    description:
      "  Total Commander (anciennement Wincmd) est un gestionnaire de fichiers  pour Windows similaire à l'explorateur Windows. Mais Total Commander  utilise une approche différente : il a deux fenêtres fixes côte à côte  comme un gestionnaire de fichiers bien connu pour le DOS.",
  },
  {
    name: "MobaXterm",
    type: "",
    weight: "26.5 Mo",
    version: "21.2 Build 4642",
    year: "",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/788896-mobaxterm+professional+edition+21+2+win+en+license",
    price: 4000,
    image: "https://i.imgur.com/IiJ9MVW.png",
    description:
      "MobaXterm est votre boîte à outils ultime pour l'informatique à distance. Dans une seule application Windows, il offre de nombreuses fonctions adaptées aux programmeurs, webmasters, administrateurs informatiques et à presque tous les utilisateurs qui ont besoin de gérer leurs travaux à distance de manière plus simple.  MobaXterm fournit tous les outils réseau à distance importants (SSH, X11, RDP, VNC, FTP, MOSH, ...) et les commandes Unix (bash, ls, cat, sed, grep, awk, rsync, ...) sur le bureau de Windows, dans un seul fichier exe portable qui fonctionne dès le départ.   Il y a de nombreux avantages à disposer d'une application réseau tout-en-un pour vos tâches à distance. Par exemple, lorsque vous utilisez SSH pour vous connecter à un serveur distant, un navigateur SFTP graphique s'affiche automatiquement afin de modifier directement vos fichiers distants. Vos applications distantes s'afficheront également de manière transparente sur votre bureau Windows grâce au serveur X intégré.  Lors du développement de MobaXterm, nous nous sommes concentrés sur un objectif simple : proposer une interface utilisateur intuitive afin de vous permettre d'accéder efficacement à des serveurs distants à travers différents réseaux ou systèmes.",
  },
  {
    name: "Sketchup Pro + V-Ray for Sketchup",
    type: "",
    weight: "1.28Go",
    version: "v22.0.354",
    year: "2022",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/884670-sketchup+pro+2022+v22+0+354+x64+fr+v-ray+for+sketchup+v5+20+05+en+win+patch",
    price: 2000,
    image: "https://www.zupimages.net/up/22/16/npb3.jpg",
    description:
      "SketchUp est un logiciel de modélisation 3D, d'animation et de cartographie orienté vers l'architecture. Initialement édité par la société @Last Software (racheté par Google ensuite), ce logiciel se caractérise par des outils simples (rotation, extrusion, déplacement, etc.), qui en font un logiciel de 3D très différent des modeleurs 3D classiques.    Vray ou (V-Ray) est un moteur de rendu utilisé comme extension pour plusieurs logiciels de modélisation 3D. C'est un moteur de rendu qui utilise des techniques avancées de synthèse d'images, comme des algorithmes d'illumination globale, de lancer de rayon, de photon mapping ou encore de radiosité. L'utilisation de ces techniques rend Vray plus attractif que la plupart des moteurs de rendu intégrés aux logiciels de modélisation, principalement parce que les rendus obtenus grâce à ces algorithmes sont plus photo-réalistes du fait de la meilleure simulation des rayons lumineux. L'utilisation de ce moteur de rendu augmente de façon plus ou moins significative le temps de rendu nécessaire à l'obtention d'une bonne image, notamment à cause de la complexité et de la quantité des calculs effectués.<br><br>INFORMATION:<br>•Système d'exploitation : Windows 10 version 1803<br>•Architecture : 64 bits<br>•Processeur : Intel 6eme génération, AMD Ryzen série 1000, GPU 2Go<br>•Mémoire vive : 4 Go<br>•Disque Dur : 30Go espace disque<br>•Carte Graphique : 4 Go",
  },
  {
    name: "AutoCAD 2023 FRANÇAIS X64 + PATCH [WIN]",
    type: "",
    weight: "2.35Go",
    version: "2023",
    year: "04/22",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/876845-autocad+2023+fran%C3%A7ais+x64+patch+win",
    price: 2000,
    image: "https://www.zupimages.net/viewer.php?id=22/13/pvl8.png",
    description:
      "AutoCAD® est un logiciel de conception assistée par ordinateur (CAO) qui permet aux architectes, aux ingénieurs et aux  professionnels de la construction de créer des dessins 2D et 3D précis.    Création, annotation et modification de géométries 2D et de modèles 3D avec des solides, des surfaces et des objets de maillage    Automatisation des tâches telles que la comparaison de dessins, le comptage, l’ajout de blocs, la création de nomenclatures, et plus encore    Personnalisation à l’aide d’applications complémentaires et d’API  ",
  },
  {
    name: "SolidWorks 2022 SP4 PREMIUM",
    type: "",
    weight: "16.08 Go",
    version: "2022 SP4 Premium",
    year: "2022",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/937873-solidworks+2022+sp4+premium+windows+x64+crack+multi9",
    price: 5500,
    image:
      "https://billeder.dba.dk/dbaboost/2284ab1a-8a45-462c-a480-dcac428f79f3.jpeg",
    description:
      "SolidWorks est un programme informatique de modélisation solide basé sur la conception assistée par ordinateur (CAO) et l'ingénierie assistée par ordinateur (CAE) fonctionnant principalement sous Microsoft Windows. Bien qu'il soit possible d'exécuter SolidWorks sur MacOS, cela n'est pas pris en charge par SolidWorks.  SolidWorks est publié par Dassault Systèmes.  Selon l'éditeur, plus de deux millions d'ingénieurs et de concepteurs travaillant dans plus de 165 000 entreprises utilisaient SolidWorks en 2013. ",
  },
  {
    name: "	Microsoft Office",
    type: "",
    weight: "",
    version: "",
    year: "",
    pack: [],
    link: "",
    price: 15,
    image: "",
    description: "",
  },
  {
    name: "ARCHICAD",
    type: "",
    weight: "2.96Go",
    version: "26 build 3001",
    year: "Juillet 2022",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/914996-archicad+26+fr+-+3001+win+x64+fr+patch",
    price: 2000,
    image:
      "https://www.graphisoft-west.de/wp-content/uploads/Archicad26-Hero-1920x1080-100-768x432.jpg",
    description:
      "Parce qu’il a posé le premier jalon dans la longue marche vers l’intégration des disciplines autour d’une maquette numérique intelligente, Archicad est aujourd’hui leader reconnu de l’Open BIM, choisi par plus de 500 000 architectes et professionnels de la construction exigeants dans le monde entier.  Fort de ses innovations pionnières comme le concept de Virtual Building qui agrège les données autour du modèle, le travail collaboratif Teamwork ou l’application BIMx, Archicad ne cesse de se réinventer dans la proposition de nouveaux flux de travail nécessaires pour satisfaire les exigences croissantes des missions de l’Architecte dans la gouvernance du projet de construction.  Conception en toute liberté, collaboration avec les autres disciplines à un niveau inédit, interopérabilité sans faille et puissants outils de documentation, de visualisation et d’exploration des projets constituent l’ADN d’Archicad, exceptionnel outil-métier pour la synthèse architecturale et technique au cœur de la maîtrise de l’Œuvre et de la gestion du BIM.<br><br>INFORMATION:<br>•Processeur : 10 64-bits avec quatre cœurs ou plus.<br>•OS  compatible : Win 10 x64<br>•Tous SAUF: Windows 8.1, Windows 8 & Windows 7 (version 64-bits)<br>•Mémoire : 16 Go recommandes. Pour des projets complexes et détailles, 32 Go ou plus peuvent être requis.<br>•Compatible Open GL 4.5 dédiée avec mémoire intégrée 2 Go ou davantage est recommandé pour pouvoir bénéficier entièrement des capacités d’accélération matérielle.<br>•Une résolution 4K de 3840 x 2160 pixels ou plus élevée est recommandée. (1440 x 900 pixels minimum est requise)",
  },
  {
    name: "Cinema 4D",
    type: "",
    weight: "696.7 MB",
    version: "R20",
    year: "",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/347784-cinema+4d+r20+windows+serial+muilti",
    price: 6000,
    image:
      "https://img2.freepng.fr/20180706/lyt/kisspng-cinema-4d-3d-computer-graphics-rendering-motion-gr-cinema-4d-logo-5b3f9b2f383a77.2759573915308951512303.jpg",
    description:
      "Cinema 4D Version 20 marque un grand saut en avant en matière de technologie, avec une nouvelle infrastructure qui vous offre une grande puissance de création. Les possibilités sont infinies et votre créativité sans bornes : il est temps de faire le grand plongeon !",
  },
  {
    name: "Nuance Dragon Professional Individual 15.61.200.010",
    type: "",
    weight: "3850 Mo",
    version: "15.61.200.010",
    year: "2017",
    pack: [],
    link: "https://www5.yggtorrent.fi/torrent/application/windows/732191-nuance+dragon+professional+individual+15+61+200+010+win+fr+crack",
    price: 2000,
    image:
      "https://media.ldlc.com/r1600/ld/products/00/05/45/95/LD0005459523_2.jpg",
    description:
      "Dopez votre productivité documentaire à la voix  Créez vos rapports, emails, formulaires et bien plus encore à l'aide de votre voix grâce à la version 15  de Dragon Professional Individual. Avec son moteur de nouvelle génération optimisé par la technologie de  Deep Learning, vous pouvez désormais dicter et transcrire plus rapidement et plus précisément que jamais,  et accélérer ainsi votre production documentaire. C'est autant de temps libéré que vous pourrez consacrer  à des activités à valeur ajoutée.",
  },
];
